### ISSUE TITLE
Is `provides` really necessary?

### ISSUE THREAD

**Issue by sporto** [jonstokes/troupe#3]
This:

```ruby
provides(:order) do
    user.orders.create(attributes)
 end
```

Seems to be equivalent to:

```ruby
def order
	@order ||= user.orders.create(attributes)
end
```

Or I'm missing something?

If so I don't think that having this extra DSL is good, it makes looking at the code more confusing. Consider removing `provides` if this is the case.

**Comment by jonstokes** [comment]
@sporto the two code blocks that you give above aren't quite equivalent. What `provides(:order)` does is to set a `:order` key on the `context` hash, so that when you've called the interactor you can call `order` on the resulting interactor object and get back the value that was set. Plus `order` is now available to the other interactors in an organizer's list.
